[project]
name = "adept"
version = "0.0.1"
authors = [
  { name="Ben Scott", email="ben@benscott.co.uk" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
]

[project.urls]
"Homepage" = "https://github.com/benscott/adept"