# https://spacy.io/usage/training
# https://spacy.io/usage/training#config
# https://explosion.ai/blog/spacy-v3-project-config-systems#spacy-config-system
# https://stackoverflow.com/questions/72904855/no-pos-tags-in-newly-trained-spacy-ner-model-how-to-enable
# https://github.com/explosion/spaCy/discussions/6777

# Transformer example: https://github.com/explosion/projects/blob/1ba2ba72ca3a0edb2dee1b8b8f0f7b2bffe53c87/tutorials/ner_pytorch_medical/configs/spacy_config_trf.cfg
# https://github.com/explosion/projects/blob/1ba2ba72ca3a0edb2dee1b8b8f0f7b2bffe53c87/tutorials/textcat_goemotions/configs/bert.cfg

# It's using tok2vec spacy-transformers

# https://github.com/explosion/spaCy/discussions/10330
# https://github.com/explosion/projects/blob/15e180e28d834ee594ea4b8154c5132d7895bc23/experimental/coref/project.yml

title: ""
description: ""

spacy_version: ">=3.3.0,<4.0.0"

vars:
  name: "adept-ner"
  lang: "en"
  version: "0.0.1"
  # Set your GPU ID, -1 is CPU
  gpu_id: 0
  vectors_model: "en_core_web_md"  
  trf_model: "en_core_web_trf"
  dir: 
    corpus: 'corpus'
    training: 'training'
    packages: 'training/packages'    
    assets: '../../data/assets'
    models: '../../data/models'
    training_vector: '${vars.dir.training}/vector'
    training_trf: '${vars.dir.training}/trf'
    config: 'config'
    scripts: 'scripts' 
  file:
    train: '${vars.dir.assets}/train-numeric.json'
    code: '${vars.dir.scripts}/components.py'
    spacy:
      train: '${vars.dir.corpus}/train_numeric.spacy'    
      test: '${vars.dir.corpus}/test_numeric.spacy' 
      val: '${vars.dir.corpus}/val_numeric.spacy' 

directories: ['corpus', 'training', "config", "scripts"]

assets:
  - dest: "${vars.file.train}"
  - dest: "${vars.dir.corpus}"
  - dest: "${vars.dir.training}"
  - dest: "${vars.dir.packages}"

workflows:
  all:
    - convert
    - fill-config
    - train
    - evaluate

commands:
  - name: "download"
    help: "Download a spaCy model with pretrained vectors"
    script:
      - "python -m spacy download ${vars.vectors_model}"

  - name: "convert"
    help: "Convert the data to spaCy's binary format"
    script:
      - python scripts/convert.py ${vars.lang} ${vars.file.train} ${vars.dir.corpus}
    deps:
      - "${vars.file.train}"
    outputs:
      - "${vars.file.spacy.train}"
      - "${vars.file.spacy.test}"
      - "${vars.file.spacy.val}"

  - name: "fill-config"
    help: "Fill config defaults"
    script:
      - "python -m spacy init fill-config ${vars.dir.config}/base_config.cfg ${vars.dir.config}/config.cfg --code ${vars.file.code}"      
      - "python -m spacy init fill-config ${vars.dir.config}/base_trf_config.cfg ${vars.dir.config}/trf_config.cfg --code ${vars.file.code}"

  - name: "train"
    help: "Train the NER model"
    script:
      - "python -m spacy train ${vars.dir.config}/config.cfg --output ${vars.dir.training_vector} --paths.train ${vars.file.spacy.train} --paths.dev ${vars.file.spacy.val} --gpu-id -1 --initialize.vectors ${vars.vectors_model} --code ${vars.file.code}"
    deps:
      - "${vars.dir.config}/config.cfg"
      - "${vars.file.spacy.train}"
      - "${vars.file.spacy.val}"
    outputs:
      - "${vars.dir.training_vector}/model-best"

  - name: "train-trf"
    help: "Train the transformer model"
    script:
      - "python -m spacy train ${vars.dir.config}/trf_config.cfg --output ${vars.dir.training_trf} --paths.train ${vars.file.spacy.train} --paths.dev ${vars.file.spacy.val} --gpu-id ${vars.gpu_id} --code ${vars.file.code}  --paths.trf_model ${vars.trf_model}" 
    deps:
      - "${vars.dir.config}/trf_config.cfg"
      - "${vars.file.spacy.train}"
      - "${vars.file.spacy.val}"
    outputs:
      - "${vars.dir.training_trf}/model-best"

  - name: "evaluate"
    help: "Evaluate the model and export metrics"
    script:
      - "python -m spacy evaluate ${vars.dir.training_vector}/model-best ${vars.file.spacy.test} --output ${vars.dir.training_vector}/metrics.json --code ${vars.file.code}"
    deps:
      - "${vars.file.spacy.test}"
      - "${vars.dir.training_vector}/model-best"
    outputs:
      - "${vars.dir.training_vector}/metrics.json"

  - name: "evaluate-trf"
    help: "Evaluate the model and export metrics"
    script:
      - "python -m spacy evaluate ${vars.dir.training_trf}/model-best ${vars.file.spacy.test} --output ${vars.dir.training_trf}/metrics.json --code ${vars.file.code} --gpu-id ${vars.gpu_id}" 
    deps:
      - "${vars.file.spacy.test}"
      - "${vars.dir.training_trf}/model-best"
    outputs:
      - "${vars.dir.training_trf}/metrics.json"

  # - name: package
  #   help: "Package the trained numeric model as a pip package"
  #   script:
  #     - "python -m spacy package ${vars.dir.training}/model-best ${vars.dir.packages} --name ${vars.name} --version ${vars.version} --force --code ${vars.file.code}"
  #   deps:
  #     - "${vars.dir.training}/numeric/model-best"
  #   outputs_no_cache:
  #     - "${vars.dir.packages}/${vars.lang}_${vars.name}-${vars.version}/dist/${vars.lang}_${vars.name}-${vars.version}.tar.gz"

  - name: visualize-model
    help: Visualize the model's output interactively using Streamlit
    script:
      - "streamlit run scripts/visualize_model.py ${vars.dir.training}/model-last \"\""
    deps:
      - "scripts/visualize_model.py"
      - "${vars.dir.training}/model-best"

  - name: "assemble"
    help: "Assemble all parts into the complete ADEPT pipeline."
    script:
      - spacy assemble ${vars.dir.config}/assemble.cfg ${vars.dir.models}/adept --code ${vars.file.code} --paths.trained_model ${vars.dir.training_trf}/model-best
    deps:
      - ${vars.dir.training_vector}/model-best
      - ${vars.dir.config}/assemble.cfg    
    outputs:
      - "${vars.dir.models}/adept"        
